### ISSUE TITLE
CamelCase in enum names for Strings?

### ISSUE THREAD

**Issue by gereons** [SwiftGen/SwiftGen#386] opened 2018-02-20 12:33 UTC
My Localizable.strings files has entries like this:

```"AppUpdate.laterButton" = "Not now"```

and I would like to see these in Strings.swift as

````
enum L10n {
    enum AppUpdate {
        static let laterButton = L10n.tr("...")
    }
}
````

I can't seem to find a way to keep the camelCasing in `AppUpdate`  intact, swiftgen always generates `Appupdate`. As far as I can tell, there is nothing I can do in `structured-swift4.stencil` to achieve this. Am I missing something?

**Comment by djbe** [comment] 2018-02-20 13:07
I'm pretty sure this is a duplicate of #257, where we discussed some possible solutions (thread is a bit older, so it might mention some older template names and stuff). Specifically I mentioned a possible solution in https://github.com/SwiftGen/SwiftGen/issues/257#issuecomment-271922641, can't remember what the rest of the discussion was.

Anyway, I'm going to close this in favour of the older issue (with more discussion). Any comments or remarks are welcome there! They might get us started again on solving this particular issue.

**Closed by djbe** 2018-02-20 13:07 UTC
