### ISSUE TITLE
Flag `ignoreTargetModule` is not working for generating `storyboards`

### ISSUE THREAD

**Issue by SergeMaslyakov** [SwiftGen/SwiftGen#405] opened 2018-04-04 09:46 UTC
Hi.

I can't suppress the adding module name in the generated `storyboard` file.
Swiftgen version `SwiftGen v5.3.0 (Stencil v0.10.1, StencilSwiftKit v2.4.0, SwiftGenKit v2.2.0)`

I have done some tests with `--verbose` + `config.yml` file. To compare a case-2 and case-3, the verbose output the same, but result is different.

1) ignoreTargetModule=true

```

//// config
storyboards:
  paths: Core/Sources/UI
  templateName: swift4
  output: StoryboardScene.swift
  params:
    ignoreTargetModule: true

//// verbose output
$ swiftgen storyboards -t swift4 --param ignoreTargetModule -o ../../Application/Generated/StoryboardScene.swift ../../Core/Sources/UI
File written: ../../Application/Generated/StoryboardScene.swift

///// import in the file StoryboardScene.swift /////
import Foundation
import UIKit
import Test

```

2) [Test]

```
//// config
storyboards:
  paths: Core/Sources/UI
  templateName: swift4
  output: StoryboardScene.swift
  params:
    module: [Test]
    
//// verbose output    
$ swiftgen storyboards -t swift4 --param module=Test -o ../../Application/Generated/StoryboardScene.swift ../../Core/Sources/UI
Not writing the file as content is unchanged

///// import in the file StoryboardScene.swift /////
import Foundation
import UIKit
import Test

```

3) Test - this case is working, but I have 3 targets in the app

```
//// config
storyboards:
  paths: Core/Sources/UI
  templateName: swift4
  output: StoryboardScene.swift
  params:
    module: Test

//// verbose output
$ swiftgen storyboards -t swift4 --param module=Test -o ../../Application/Generated/StoryboardScene.swift ../../Core/Sources/UI
File written: ../../Application/Generated/StoryboardScene.swift

///// import in the file StoryboardScene.swift /////
import Foundation
import UIKit

```

**Comment by djbe** [comment] 2018-04-04 15:32
Are your storyboards shared between those 3 targets?

**Comment by SergeMaslyakov** [comment] 2018-04-04 15:35
Yea. Exactly

**Comment by djbe** [comment] 2018-04-04 15:41
Right, the issue is then that Xcode will do something automatically, namely that whenever you open a storyboard and select a scene, it'll change the "module" in the storyboard to the currently selected target.

When you execute SwiftGen as a build phase, it'll detect the `module` you are building and pass this along to the template. Additionally, you can provide a second `module` as a parameter, and SwiftGen will ignore both the parameter module and the build phase module. Currently SwiftGen doesn't accept a third `module`, or a list of `modules` to ignore.

You've got 2 options:
- Create your own template, where you perform checks for extra modules using (for example) additional parameters or environment variables.
- Create a PR to change the `module` parameter to accept multiple values. This is a breaking change though (for current users), so chances of this getting merged very soon might be a bit low.

**Comment by SergeMaslyakov** [comment] 2018-04-04 15:58
Thanks for explanation.

Correct me if I'm wrong, but this option `ignoreTargetModule=true` should exclude all module mentions in the generated file? But it is not working.

I have found similar issues in issues-history and as I understand it was added for that purpose.

**Comment by djbe** [comment] 2018-04-04 16:00
It's for only ignoring the current target (quote from the docs):
> Setting this parameter will disable the behaviour of prefixing classes with their module name for (only) the target module.

The issue here is that your current "target" (from environment variables) and the module in your storyboard do not match. You can provide an additional one via the `module` parameter, but that still won't help you because you have a *third* potential target.

**Closed** 2018-04-04 16:13 UTC

**Comment by AliSoftware** [comment] 2018-04-04 20:00
> Create a PR to change the module parameter to accept multiple values. This is a breaking change though (for current users), so chances of this getting merged very soon might be a bit low.

I'd be ok with a PR supporting a list of modules as long as it's backwards compatible. That is, make the `module` parameter be an array, _but_ if you provide a single string (like what's currently supported) it would be interpreted as an array with that single element.

**Comment by AliSoftware** [comment] 2018-04-04 20:02
In the meantime as @djbe suggested the easiest solution is to create a custom template, which is really easy to do (duplicate an existing one then adapt, see documentation)

**Comment by djbe** [comment] 2018-04-04 20:27
> That is, make the module parameter be an array, but if you provide a single string (like what's currently supported) it would be interpreted as an array with that single element.
Problem is, that'd be a breaking change for current templates (I think)
