### ISSUE TITLE
Missing ARM brew bottle

### ISSUE THREAD

**Issue by stuffmc** [SwiftGen/SwiftGen#820] opened 2021-02-12 16:23 UTC

**Comment by FelixLisczyk** [comment] 2021-02-17 10:52
I can confirm this issue.

```
% brew install swiftgen
Error: swiftgen: no bottle available!
You can try to install from source with:
  brew install --build-from-source swiftgen
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

I also get the following errors when trying to build the bottle from source on an M1 MacBook Air:

```
% brew install --build-from-source swiftgen
==> Cloning https://github.com/SwiftGen/SwiftGen.git
Updating /Users/felix/Library/Caches/Homebrew/swiftgen--git
==> Checking out tag 6.4.0
HEAD is now at 0c67b63 Merge pull request #792 from SwiftGen/hotfix/brew-cli-install
HEAD is now at 0c67b63 Merge pull request #792 from SwiftGen/hotfix/brew-cli-install
==> gem install bundler
==> bundle install --without development release
==> bundle exec rake cli:install[/opt/homebrew/Cellar/swiftgen/6.4.0/bin,/opt/homebrew/Cellar/swiftgen/6.4.0/lib,/opt/homebrew/Cel
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/swiftgen/6.4.0/lib/Commander.framework/Versions/A/Commander
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/swiftgen/6.4.0/lib/Kanna.framework/Versions/A/Kanna
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/swiftgen/6.4.0/lib/PathKit.framework/Versions/A/PathKit
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/swiftgen/6.4.0/lib/Stencil.framework/Versions/A/Stencil
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/swiftgen/6.4.0/lib/StencilSwiftKit.framework/Versions/A/StencilSwiftKit
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/swiftgen/6.4.0/lib/SwiftGenKit.framework/Versions/A/SwiftGenKit
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/swiftgen/6.4.0/lib/Yams.framework/Versions/A/Yams
🍺  /opt/homebrew/Cellar/swiftgen/6.4.0: 203 files, 19.9MB, built in 41 seconds
```

I'm running macOS 11.2.1 and have the Xcode Command Line Tools installed.

**Comment by mudithsilva** [comment] 2021-05-11 08:39
I checked in Mint installation and it's working fine on Apple Silicon.
Try :- 

To install Mint:- brew install mint
To Install SwiftLint:- sudo mint install realm/SwiftLint
To Install SwiftGen:- sudo mint install SwiftGen/SwiftGen
To manually run the SwiftLint and SwiftGen (navigate to project folder) :- mint run swiftgen and mint run swiftlint

**Comment by djbe** [comment] 2021-05-25 12:19
Closing this as a duplicate of #805. Hope to create a release in the coming week.

**Closed as completed by djbe** 2021-05-25 12:19 UTC
Labels: duplicate
