### ISSUE TITLE
Allow wildcards in input paths

### ISSUE THREAD

**Issue by fengqiangboy** [SwiftGen/SwiftGen#412] opened 2018-04-18 12:22 UTC
Can use this path in config file?

```
/path/to/dir/**/*. xcassets
```

**Comment by djbe** [comment] 2018-05-05 23:52
Marking this as a duplicate of #383. Once filter support is built in, we'll just have to modify all commands to accept folders as input, and have the parsers search recursively as needed.

**Closed by djbe** 2018-05-05 23:52 UTC
Labels: type: enhancement
