### ISSUE TITLE
IB: Generated Code imports Foundation only – build fails

### ISSUE THREAD

**Issue by Dschee** [SwiftGen/SwiftGen#521] opened 2018-09-29 21:56 UTC
Hi, I just upgraded to SwiftGen 6.0 and here's my command:

```shell
swiftgen ib "$PROJECT_DIR/App/Sources" -t scenes-swift4 -o "$PROJECT_DIR/App/Generated/SwiftGen/Storyboards.swift"
```

The output looks like the following:

```swift
// swiftlint:disable all
// Generated using SwiftGen, by O.Halligon — https://github.com/SwiftGen/SwiftGen

// swiftlint:disable sorted_imports
import Foundation

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - Storyboard Scenes

// swiftlint:disable explicit_type_interface identifier_name line_length type_body_length type_name
internal enum StoryboardScene {
  internal enum BottomNavigation: StoryboardType {
    internal static let storyboardName = "BottomNavigation"

    internal static let initialScene = InitialSceneType<App.BottomNavigationViewController>(storyboard: BottomNavigation.self)
  }
  internal enum BottomSheet: StoryboardType {
    internal static let storyboardName = "BottomSheet"

    internal static let initialScene = InitialSceneType<App.BottomSheetViewController>(storyboard: BottomSheet.self)
  }
}
// swiftlint:enable explicit_type_interface identifier_name line_length type_body_length type_name

// MARK: - Implementation Details

internal protocol StoryboardType {
  static var storyboardName: String { get }
}

internal extension StoryboardType {
  static var storyboard: UIStoryboard {
    let name = self.storyboardName
    return UIStoryboard(name: name, bundle: Bundle(for: BundleToken.self))
  }
}

internal struct SceneType<T: UIViewController> {
  internal let storyboard: StoryboardType.Type
  internal let identifier: String

  internal func instantiate() -> T {
    let identifier = self.identifier
    guard let controller = storyboard.storyboard.instantiateViewController(withIdentifier: identifier) as? T else {
      fatalError("ViewController '\(identifier)' is not of the expected class \(T.self).")
    }
    return controller
  }
}

internal struct InitialSceneType<T: UIViewController> {
  internal let storyboard: StoryboardType.Type

  internal func instantiate() -> T {
    guard let controller = storyboard.storyboard.instantiateInitialViewController() as? T else {
      fatalError("ViewController is not of the expected class \(T.self).")
    }
    return controller
  }
}

private final class BundleToken {}
```

As you can see, at the top there's only `import Foundation` but within the file there are several references to UIKit types like `UIViewController`. Therefore my builds are failing with errors stating:

```
App/Generated/SwiftGen/Storyboards.swift:53:37: Use of undeclared type 'UIViewController'
```

Am I using it wrong or is this an issue with my specific setup? Here's my environment info:

- SwiftGen v6.0.0 (Stencil v0.13.1, StencilSwiftKit v2.7.0, SwiftGenKit v6.0.0)
- Version 10.0 (10A255)
- macOS 10.14 Mojave

**Comment by AliSoftware** [comment] 2018-09-29 21:59
Probably already fixed by https://github.com/SwiftGen/SwiftGen/pull/519 ? :wink:

The import is missing because you have no scene in your SB. Try to add at least one scene with an identifier in your storyboard. If it fixes it, then that confirms that #519 will completely solve your problem even when no scene is present :wink:

**Comment by Dschee** [comment] 2018-09-29 22:03
What do you mean by a "scene"? I'm only using initial scenes, so I didn't need an identifier, but I just added Storyboard IDs to my view controllers, which didn't help, the output was still not including 'import UIKit'. But if you say #519 will fix it, then I'm good with that. 👍

**Comment by djbe** [comment] 2018-09-29 22:04
Seeing the output you posted, and 99% sure that #519 is the fix you need. This is a duplicate of #515.

**Closed by djbe** 2018-09-29 22:04 UTC
