### ISSUE TITLE
SwiftGen does not work if two different outputs with same input

### ISSUE THREAD

**Issue by Igor-Palaguta** [SwiftGen/SwiftGen#650] opened 2019-07-25 12:46 UTC
Just last color command is executed
```yaml
xcassets:
  inputs:
    - Color.xcassets
  outputs:
    templatePath: UIColor.stencil
    output: UIColor+AssetCatalog.swift

xcassets:
  inputs:
    - Color.xcassets
  outputs:
    templatePath: SwiftUI-Color.stencil
    output: Color+AssetCatalog.swift
```

```
swiftgen --version
SwiftGen v6.1.0 (Stencil v0.13.1, StencilSwiftKit v2.7.2, SwiftGenKit v6.1.0)
```

**Comment by djbe** [comment] 2019-07-25 13:58
Duplicate of #649.

Check the [Configuration File Format](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/ConfigFile.md#configuration-file-format) documentation, for multiple invocations of the same command.

**Closed as completed by djbe** 2019-07-25 13:58 UTC
Labels: duplicate

**Comment by Igor-Palaguta** [comment] 2019-07-25 20:33
@djbe Thanks!

Probably swiftlint should show warning in this case?

**Comment by Igor-Palaguta** [comment] 2019-07-26 08:21
I see it is not issue with config it is yaml, it will be the same in json
```json
{
"xcassets": {},
"xcassets": {}
}
```

**Comment by eroth** [comment] 2020-12-11 05:48
Just ran across this issue myself—in case others do, too, here's the correct implementation based on the OP's example:

    xcassets:
      inputs:
        - Color.xcassets
      outputs:
        - templatePath: UIColor.stencil
           output: UIColor+AssetCatalog.swift
        - templatePath: SwiftUI-Color.stencil
           output: Color+AssetCatalog.swift
