### ISSUE TITLE
Seems android colors.xml with alpha is parsed incorrectly

### ISSUE THREAD

**Issue by apozdeyev** [SwiftGen/SwiftGen#616] opened 2019-02-28 17:03 UTC
Hi All!
First of all, thank you for the useful tool!
I am trying to use SwiftGen in our project in order to reuse colors from android app in iOS app. But I faced with a problem that colors with alpha component is parsed incorrectly, alpha and red components are swapped.

We use SwiftGen v6.1.0 (Stencil v0.13.1, StencilSwiftKit v2.7.2, SwiftGenKit v6.1.0)

Example of parsed colors.xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<resources>
    <color name="color">#01223344</color>
</resources>
```
Command line we use to generate swift class:
`SwiftGen colors --output ./colors.swift --templateName literals-swift4 ./colors_test.xml`

And result swift class:
```
// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(OSX)
  import AppKit
  internal enum ColorName { }
#elseif os(iOS) || os(tvOS) || os(watchOS)
  import UIKit
  internal enum ColorName { }
#endif

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - Colors

// swiftlint:disable identifier_name line_length type_body_length
internal extension ColorName {
  /// 0x01223344 (r: 1, g: 34, b: 51, a: 68)
  internal static let color = #colorLiteral(red: 0.003921569, green: 0.13333334, blue: 0.2, alpha: 0.26666668)
}
// swiftlint:enable identifier_name line_length type_body_length
```

Accordint to the [google documentation](https://developer.android.com/guide/topics/resources/more-resources#Color) color value format is #AARRGGBB, but SwiftGen seems uses #RRGGBBAA.

Please, clarify is it a bug? May be it is possible to configure parsing format somehow?

**Comment by djbe** [comment] 2019-02-28 17:08
Hi @apozdeyev,

Thank you for reporting the issue. This is a duplicate of #562, we're we've already discussed how to fix & implement this. If you have further comments or requests related to android color parsing, please mention it there.

**Closed as completed by djbe** 2019-02-28 17:08 UTC
Labels: duplicate

**Comment by kevinstier** [comment] 2020-10-07 09:56
@apozdeyev from [6.4.0](https://github.com/SwiftGen/SwiftGen/releases/tag/6.4.0), the colors XML parser accepts a `colorFormat` option. See the [documentation](https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/Parsers/colors.md#customization) on how to use it.
