### ISSUE TITLE
Assets catalogue color asset for below iOS 11

### ISSUE THREAD

**Issue by andrewlord1990** [SwiftGen/SwiftGen#388] opened 2018-02-22 16:24 UTC
Would it be at all possible to pull the color value out when parsing the Assets catalog?

This would allow SwiftGen to generate UIColor instances from the Assets catalog that can be used below iOS 11.

**Comment by djbe** [comment] 2018-02-22 16:38
This has already been discussed, and it's pretty much impossible, because a color "asset" doesn't have just 1 color, it can be a whole bunch of colors depending on some device parameters. 

Dupe of #341.

**Closed by djbe** 2018-02-22 16:38 UTC
Labels: duplicate

**Comment by andrewlord1990** [comment] 2018-02-22 16:45
Okay thank you for letting me know. Sorry I searched for related issues, but couldn't find any with the search terms I tried. Thanks for the explanation, shame.
