### ISSUE TITLE
tvOS brand assets

### ISSUE THREAD

**Issue by yonaskolb** [SwiftGen/SwiftGen#287] opened 2017-04-05 02:50 UTC
tvOS by default includes a `.brandAssets` folder within the main asset catalog that contains app icons and topshelf images. 
https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/BrandAssetsType.html

When this is present no images at all are generated, even other images in the assets catalog. 
If this is changed to a normal folder it works, but I don't know if iTunes will accept the asset catalog in the non standard format

**Comment by djbe** [comment] 2017-04-05 13:21
This is a duplicate of #228. 

There currently is no fix for this as it's a bug in `actool`. What you can try is to separate your assets into 2 asset catalogs, and just run `swiftgen` on the catalog with no brand assets.

**Closed by djbe** 2017-04-05 13:21 UTC
Labels: duplicate
