### ISSUE TITLE
xcassets ignores "Provides Namespace"

### ISSUE THREAD

**Issue by pjechris** [SwiftGen/SwiftGen#453] opened 2018-07-18 10:01 UTC
According to documentation, xcassets templates "take into account any namespacing folder in your Assets Catalogs". Yet no matter what value this option is, generated code is always the same.

SwiftGen
```swift
/// with "Provides Namespaces" unchecked on "Member" folder
let image = Asset.Member.profilSupp.image

/// with "Provides Namespaces" checked  on "Member" folder
let image = Asset.Member.profilSupp.image
```

R.swift

```swift
/// with "Provides Namespaces" unchecked on "Member" folder
let image = R.image.profil_supp

/// with "Provides Namespaces" checked on "Member" folder
let image = R.image.member.profil_supp
```

Tested with SwiftGen 5.3.0.

**Comment by AliSoftware** [comment] 2018-07-18 10:13
Did you check the "Provides namespace" checkbox on your folders/groups you created in your at catalog?

**Comment by AliSoftware** [comment] 2018-07-18 10:18
![](https://i.stack.imgur.com/1YX2d.png)

**Comment by djbe** [comment] 2018-07-18 10:19
What we mean with it is that the default templates take into account wether the key should be "profile_supp" or "Member/profile_supp" when calling the `.init(named: )`. The structure of the generated enums doesn't take this into account though.

You could write a template that checkes wether the key contains the group name or not, and if so create a sub-enum or not. We could add this behaviour to the built-in templates, some sort of flag to `onlyProvidesNamespaces` or something.

**Comment by pjechris** [comment] 2018-07-18 11:57
@AliSoftware Yes and it is unchecked.
@djbe So the behaviour I see is correct and there is no bug, right? In that case I've been misleaded by documentation and R.swift behaviour, sorry!

**Comment by AliSoftware** [comment] 2018-07-18 12:31
Yeah the behavior is correct/intented, we only rely on the "provides namespace" feature of xcassets to create the structure/hierarchy, so that it matches what's committed by Xcode.

We could indeed imagine changing this behavior and always consider groups — even the ones with "provides namespace" unchecked/not enabled — to provide a namespace in the generated constants anyway, but it's more logical to me to tell people to enable namespaces in their xcasset catalog if they want that feature. It's as simple as checking a box after all and gets your assets better orgamized

**Comment by pjechris** [comment] 2018-07-18 13:03
@AliSoftware From my understanding that's what SwiftGen does actually. I'll try to re-explain my point :)

I have a xcasset folder with **namespace unchecked**:
<img width="254" alt="screen shot 2018-07-18 at 11 54 11" src="https://user-images.githubusercontent.com/7334856/42882983-942619cc-8a9a-11e8-842e-49245517ca8a.png">

Yet SwiftGen generates a namespaced constant (`Asset.Member.profilSupp.image`) for it while R.Swift does not (`R.image.profil_supp`)

From @djbe comment it is indeed intended behaviour, but from yours... it seems not :D

**Comment by AliSoftware** [comment] 2018-07-18 13:08
Ohhh ahah yeah I might have been confused and just did a Trump and telling the opposite of what is the intended behaviour 😂  tbh I know that there has been a choice here in SwiftGen (either rely on the folder structure to create sub-structures in the generated constants, or rely on the "Provides namespace"), but now I'm not sure which of the two choices we ended up choosing (I've replied to you above on a rush without checking anything).

What's important is that it's currently definitely one or the other but not both (i.e. it can't currently be customized by an existing flag that would be provided in the bundled templates)

**Comment by djbe** [comment] 2018-07-18 13:20
We should propagate the `namespaced` property from our parser to the context, and we could add a flag to the bundled template to toggle the behaviour.

Propagating the flag is really easy. Adjusting the template is hard, because I hate naming things 😆 (need a name for the flag to toggle the behaviour)

**Comment by pjechris** [comment] 2018-07-18 14:42
I'll take a look see if I can do it

**Closed** 2018-08-31 22:32 UTC
Labels: difficulty: easy, type: enhancement
