### ISSUE TITLE
[Strings-DotSyntaxSwift3] Named Placeholders

### ISSUE THREAD

**Issue by Dschee** [SwiftGen/SwiftGen#274] opened 2017-03-03 13:00 UTC
I was just using a key like `MAX_SPEED_EXCEEDED_NOTIFICATION.MESSAGE` in my code which generates to `L10n.MaxSpeedExceededNotification.message(50, "mi/h")` on the usage side. The value in the Strings file is something like `Max speed of %d %@ exceeded`.

It is not clear though for both the translator and also the programmer what these placeholders stand for. Both need to guess some part of it.

Natural Approach
---
Wouldn't it be better if we could write something like:

```
MAX_SPEED_EXCEEDED_NOTIFICATION.MESSAGE(MAX_SPEED_VALUE,MAX_SPEED_UNIT)
```

The translator would immediately know what the two stand for and could look up the correct order in the source translation (e.g. English). We could build the given parentheses structure into a template so the usage in code would look like this: 
```
L10n.MaxSpeedExceededNotification.message(maxSpeedValue: 50, maxSpeedUnit: "mi/h")
```
This would also make sure every programmer using the API or reading the code knows exactly what's going on.

Extensive Approach
---
Alternatively we could also build our own replacement logic. For example, using the common environment variable prefix `$` a key could look something like this: 
```
MAX_SPEED_EXCEEDED_NOTIFICATION.MESSAGE($MAX_SPEED_VALUE,$MAX_SPEED_UNIT)
```

Then the translation value could even be easier for a translator to manage:
```
Max speed of $MAX_SPEED_VALUE $MAX_SPEED_UNIT exceeded
```
The translations would also be much more readable. Of course we would not only write a new template, but also a replacement logic into the SwiftGenKit library that would automatically search a translation for the placeholders defined in the key and replace them accordingly. Usage would then be the same as in the above idea:
```
L10n.MaxSpeedExceededNotification.message(maxSpeedValue: 50, maxSpeedUnit: "mi/h")
```
The main advantage of this alternative approach would be that translators wouldn't have to deal with things like `%@` or `%d`.

**Comment by AliSoftware** [comment] 2017-03-03 13:05
Isn't it a duplicate of #242 ?

**Comment by djbe** [comment] 2017-03-03 13:11
It is. Closing this, all remaining discussion should happen there.

On another note: you really shouldn't translate your strings like that. It's better to just have one parameter "speed" and use a dedicated formatter to generate the correct spring based on value and units. There are many built-in formatters, or 3rd party libraries for this exact purpose such as [FormatterKit](https://github.com/mattt/FormatterKit).

**Comment by Dschee** [comment] 2017-03-03 13:11
It is, indeed, I couldn't find it via search though by searching for "named placeholders". Thanks for the pointer!

**Closed by djbe** 2017-03-03 13:11 UTC
Labels: type: enhancement

**Comment by Dschee** [comment] 2017-03-03 13:14
@djbe Thanks for your notice, I actually made this up to have a multiple parameters example, the real entry looks like this:
```
"GPS.TRACKING.MAX_SPEED_EXCEEDED_NOTIFICATION.MESSAGE(MAX_SPEED)" = "Maximum speed for chosen vehicle of %@ exceeded";
```
