### ISSUE TITLE
Spare import definition

### ISSUE THREAD

**Issue by RomanVolkov** [SwiftGen/SwiftGen#264] opened 2017-02-14 05:42 UTC
I'm generating StoryboardEnums and now I have started to receive such warnings

/Users/romanvolkov/Coding/Snapajob/Snapajob/EnumStoryboards.swift:5:8: File 'EnumStoryboards.swift' is part of module 'Snapajob'; ignoring import

And at the top of EnumStoryboard I see 
import Foundation
import UIKit
**import Snapajob**

Why swiftgen added this import statement? this file added to main (Snapajob) module. 

SwiftGen Script (goes right after Target Dependencies and [CP] Check Pod manifest):
`if which swiftgen >/dev/null; then
swiftgen images  "$PROJECT_DIR/Snapajob/Assets.xcassets" -t swift3 --output "$PROJECT_DIR/Snapajob/EnumImages.swift"
swiftgen storyboards "$PROJECT_DIR/Snapajob/" -t swift3 --output "$PROJECT_DIR/Snapajob/EnumStoryboards.swift"
swiftgen fonts "$PROJECT_DIR/Snapajob/Fonts/" -t swift3 --output "$PROJECT_DIR/Snapajob/EnumFonts.swift"
else
echo "warning: SwiftGen not installed, download it from https://github.com/AliSoftware/SwiftGen"
fi`

**Comment by AliSoftware** [comment] 2017-02-14 09:20
Hi and thanks for the report

This is a duplicate of #254

SwiftGen needs to generate import statements, because if you use ViewControllers comping from another module/framework in your storyboards file, it needs to import that module/framework to be able to compile. So we can't really remove those otherwise it won't compile for people using VCs from other modules (which is more and more common for people splitting their projects in multiple frameworks for separation of concerns and for compile time optimisations)

We plan too fix that very soon (after the next big release) by allowing to provide the name of your app module ("Snapajob" in your case) from the command line, so that when SwiftGen generate the list of imports for all modules it encountered in your Storyboards, it can make an exception and skip the one for your app, but still include the one for your other modules that would be required for compiling. That will be addressed by #253 for which we already have work done (and just need to finish our big refactoring in progress before merging it).

In the meantime, the solution is very easy for you:

* Duplicate the template you want to use, e.g. using `swiftgen templates cat storyboards-swift3 >storyboards-noimport.stencil` (if you use the `swift3` template for your storyboards as your script suggests) to copy its content into a new file named `storyboards-noimport.stencil`
* Modify the `storyboards-noimport.stencil` file to remove the `{% for … %}` loop at the top which is responsible for generating the import statements
* Then you can simply use `--templatePath storyboards-noimport.stencil` in your invocation of `swiftgen` to use your custom template, instead of using `-t swift3` to use the embedded swift3 template

I'm closing this issue as a duplicate, please continue any follow-up in #254

**Closed by AliSoftware** 2017-02-14 09:20 UTC

**Comment by RomanVolkov** [comment] 2017-02-19 10:22
@AliSoftware thanks for detailed explanation! it's not urgent, so  I might wait until you implement it in new release.

**Comment by AliSoftware** [comment] 2017-02-19 15:50
This has been fixed in Swift 4.2.0 which has been proposed to Homebrew just now!
See [this CHANGELOG](https://github.com/SwiftGen/templates/blob/1.0.0/CHANGELOG.md#bug-fixes) for more details.

It will be available in homebrew as soon as https://github.com/Homebrew/homebrew-core/pull/10132 is merged.
