### ISSUE TITLE
Help, Missing entry for key Error

### ISSUE THREAD

**Issue by SummerHF** [SwiftGen/SwiftGen#438] opened 2018-06-06 03:40 UTC
always show me  `Missing entry for key xcassets.paths.`, but i did add correct path i think.
**My test project structure:**
![screen shot 2018-06-06 at 11 36 02 am](https://user-images.githubusercontent.com/13494694/41015663-db46c740-697d-11e8-9161-04c0d2af2725.png)
**and my swiftgen.yml is this:**
![screen shot 2018-06-06 at 11 37 21 am](https://user-images.githubusercontent.com/13494694/41015715-148488f8-697e-11e8-8405-fd190ef7b479.png)

difficult to understand why always failure.
**the error is:**
![screen shot 2018-06-06 at 11 39 14 am](https://user-images.githubusercontent.com/13494694/41015761-486b278a-697e-11e8-85ce-822eba849e58.png)

**Comment by AliSoftware** [comment] 2018-06-06 09:42
Hi @SummerHF !

The error message is trying to tell you that your `swiftgen.yml` miss an `paths:` sub-entry in the `xcassets:` entry.

The problem is that, in the currently last released version of SwiftGen, the `swiftgen.yml` config file expect the inputs files to be under a `paths:` key, and indeed we have renamed that key in our code recently to `inputs:` instead… but that change is in the `master` branch but still not released in an official version yet (it will be part of the next upcoming release).

So what lead you to the confusion is that if you look at `master` and the `README.md` or docs that are in `master`, you'll indeed see the new docs… that correspond to that new param name not yet released. While if you go back to the tag corresponding to your installed version, the docs will use `paths:` in the doc and examples.

We realize that it's confusing — the docs in the README and home page of the GitHub pointing to master so to stuff not yet released — and we're planning to improve that in a near future — see #432, or more likely https://github.com/SwiftGen/swiftgen.github.io/issues/1 : we plan on having a dedicated documentation website/docset in the future and make it more clear which version each doc are documenting.

In the meantime, all you have to do is remplace `- inputs:` with `- paths:` (to continue using the old config key name) until the new version is released (and the new key name indeed takes it place)

**Comment by djbe** [comment] 2018-06-06 12:28
Note: this is a dupe of #431.

**Closed by djbe** 2018-06-06 12:28 UTC
Labels: duplicate

**Comment by SummerHF** [comment] 2018-06-06 13:59
Thank you very much. I have solved this problem. The process is very painful, you know it's not very difficult technical problems but all about your configuration need correct. May add a short tutorial video or provide a detailed document which i think may very helpful....
