### ISSUE TITLE
plurals support

### ISSUE THREAD

**Issue by ChocOZerO** [SwiftGen/SwiftGen#466] opened 2018-08-02 10:04 UTC
- The version of SwiftGen you're using : SwiftGen v5.3.0 (Stencil v0.10.1, StencilSwiftKit v2.4.0, SwiftGenKit v2.2.0)
- The template you're using, and any parameter you passed to it : just for strings
- The command line invocation you're using : swiftgen strings {custom}/Localizable.strings -t structured-swift4 --param enumName={custom}

I want to change my string depends on some parameters like 1 for "1 apple" or 2 for "2 apples" in a same sentence "%d %@". Is there any solution for that?

**Comment by ChocOZerO** [comment] 2018-08-02 10:05
I asked this problem to "@aligatr" on twitter. And I got answer.

"Yes, use stringdict files, they are made for that. Please look at the doc and use GitHub issues to share your questions."

thanks :)

**Comment by AliSoftware** [comment] 2018-08-02 10:07
Simply use a `Localized.stringdict` file. This isn't really specific to SwiftGen, as it's an is thing. See Apple documentation on localizing your app and managing plurals in localized strings.

**Comment by AliSoftware** [comment] 2018-08-02 10:09
Closed as duplicate of 
https://github.com/SwiftGen/SwiftGen/issues/184#issuecomment-276923737 which provides ask the details already.

**Closed by AliSoftware** 2018-08-02 10:09 UTC
Labels: type: question
