### ISSUE TITLE
SwiftGen 6.5.1 crash (installed via Mint)

### ISSUE THREAD

**Issue by goodocy** [SwiftGen/SwiftGen#905] opened 2021-12-01 11:13 UTC
Hi.
Make a good tool, so I always use it well

Crash problems are found and reported.

**image.yml**
```
xcassets:
  inputs:
    - Resource/Test.xcassets
  outputs:
    - templateName: swift5
      output: Image/Image.swift
```
then
```
SwiftGenCLI/resource_bundle_accessor.swift:11: Fatal error: could not load resource bundle: from /Users/user/.mint/bin/SwiftGen_SwiftGenCLI.bundle or /private/var/folders/hy/_f54gj0n1ns2dttw7d19rl0m0000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/SwiftGen_SwiftGenCLI.bundle
[1]    74018 trace trap  swiftgen config run --config image.yml
```

and i found same result ( happens anywhere (with or without swiftgen.yml ) )
```
swiftgen template list
```
```
SwiftGenCLI/resource_bundle_accessor.swift:11: Fatal error: could not load resource bundle: from /Users/user/.mint/bin/SwiftGen_SwiftGenCLI.bundle or /private/var/folders/hy/_f54gj0n1ns2dttw7d19rl0m0000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/SwiftGen_SwiftGenCLI.bundle
[1]    74610 trace trap  swiftgen template list
```

after a little analysis, I got some hints

**swiftgen bin**
```
lrwxr-xr-x  1 user  staff    80B Dec  1 19:52 swiftgen -> /Users/user/.mint/packages/github.com_SwiftGen_SwiftGen/build/6.5.1/swiftgen
```

```
/Users/user/.mint/packages/github.com_SwiftGen_SwiftGen/build/6.5.1
drwxr-xr-x  3 user  staff    96B Dec  1 19:52 SwiftGen_SwiftGenCLI.bundle
-rwxr-xr-x  1 user  staff   5.1M Dec  1 19:52 swiftgen
```
And after moving to the actual path
```
./swiftgen template list -> success
swiftgen template list -> fail
```

It seems that `swiftgen` does not properly recognize the `SwiftGen_SwiftGenCLI.bundle` path when installing with `mint`

please check

**Comment by djbe** [comment] 2021-12-02 22:23
Hi @goodocy 

There seems to be something wrong with your installation, the path to the bundle that Swift is trying to load is wrong. Note that SwiftGen doesn't do this, the system (Swift / SPM) does it for us.

Mint itself does not support SPM resource bundles yet, so we had to add a workaround for it with our 6.5.0 release, which was fixed in 6.5.1. See the [issue here](https://github.com/SwiftGen/SwiftGen/issues/883) and the related [Mint issue](https://github.com/yonaskolb/Mint/issues/223).

Make sure you're using the latest Mint version, and if needed reinstall it & SwiftGen. If the issue persists, I'd recommend creating an issue in the Mint repo.

**Comment by psiwork** [comment] 2021-12-14 10:07
Same problem for me.

**Comment by daidongon** [comment] 2021-12-20 09:41
me too in 6.5.1.

**Comment by djbe** [comment] 2022-02-04 02:26
As I said before, this is (afaik) a Mint issue, not a SwiftGen issue. Going to close this for now.

**Closed as completed by djbe** 2022-02-04 02:26 UTC
Labels: duplicate

**Comment by Fab1n** [comment] 2022-11-06 12:57
I think this issue still is not resolved in any way, even if it hasn't anything to do with SwiftGen. It doesn't work and we need to think about a possible fix or at least a workaround. What do you think guys?


**Here is the essence of the issue:**
`~/.mint/bin` contains a symlink called `swiftgen` which links to the actual bin `~/Users/letsbundle/.mint/packages/github.com_SwiftGen_SwiftGen/build/6.6.2/swiftgen`.
Alongside with `swiftgen` in the original bin path `SwiftGen_SwiftGenCLI.bundle` is located.

When calling `swiftgen` from commandline somehow the binary/swift/spm expects `SwiftGen_SwiftGenCLI.bundle` to be located inside `~/.mint/bin/` where the symlink is located.

Copying the bundle to `~/.mint/bin/` solves the crash.

This needs another fix in some way.

Env:
```
mint --version
Version: 0.17.2
```

```
swiftgen --version
SwiftGen v6.6.2 (Stencil v0.15.1, StencilSwiftKit v2.10.1, SwiftGenKit v6.6.2)
```

**Comment by knox** [comment] 2023-03-07 14:15
I second @Fab1n that this issue is not resolved or suffering a regression.

```
❯ mint --version
Version: 0.17.5
❯ swiftgen --version
SwiftGen v6.6.2 (Stencil v0.15.1, StencilSwiftKit v2.10.1, SwiftGenKit v6.6.2)
```

Workaround
```
❯ ln -s ~/.mint/packages/github.com_SwiftGen_SwiftGen/build/6.6.2/SwiftGen_SwiftGenCLI.bundle ~/.mint/bin/SwiftGen_SwiftGenCLI.bundle
```

**Comment by cassianomonteiro** [comment] 2023-05-11 21:55
I'm also facing this issue. The workaround worked for me.
