### ISSUE TITLE
Strings: version 6.6.x is slow

### ISSUE THREAD

**Issue by sebids** [SwiftGen/SwiftGen#987] opened 2022-08-01 12:31 UTC
SwiftGen from version 6.6.0 up is very slow compared to 6.5.1.
I have a Strings-File with 1350 Lines. Version 6.5.1 takes 0.2 seconds to run, 6.6.x takes > 120 Seconds.

Anyone else having this?

My system is a MBP 16 M1 Pro, macOS 12.4. Xcode 13.4.1

**Comment by djbe** [comment] 2022-08-01 13:35
Do you have a sample strings file we can verify this with? We need to test where the issue is (the parser, the context generator, stencil itself).

Because right now it could be any of these:
- File comments parser (added in the strings parser)
- Stencil 0.15 with whitespace control
- Template changes

**Comment by djbe** [comment] 2022-08-01 16:46
Allright I created a 1000 entries strings file for testing, and easily reproduced the issue. It's because of the new strings comments parser, more specifically at this line:
https://github.com/SwiftGen/SwiftGen/blob/stable/Sources/SwiftGenKit/Parsers/Strings/FileTypeParser/StringsFileWithCommentsParser.swift#L107

Apparently that whole thing is going to need a rewrite.

**Comment by djbe** [comment] 2022-08-01 20:23
@sebids created a PR with a fix, mind giving that a try with your setup/configuration?

**Comment by sebids** [comment] 2022-08-02 05:54
> @sebids created a PR with a fix, mind giving that a try with your setup/configuration?

That was a fast fix. And it works as fast as the old version. :-)

**Comment by djbe** [comment] 2022-08-14 02:04
Fixed in 6.6.2

**Closed as completed by djbe** 2022-08-14 02:04 UTC
Labels: type: bug/fix
