### ISSUE TITLE
SwiftGen config warnings are invisible in Xcode

### ISSUE THREAD

**Issue by Igor-Palaguta** [SwiftGen/SwiftGen#547] opened 2018-10-08 15:03 UTC
SwiftGen v6 warnings are not shown as warnings in Xcode 10. Probably warning message should start immediately with `warning:` and not with `swiftgen: warning:`

e.g. Xcode output without exclamation sign
<img width="629" alt="screen shot 2018-10-08 at 18 00 39" src="https://user-images.githubusercontent.com/800044/46616886-2da74c00-cb24-11e8-93ce-e15c7b1429da.png">

**Comment by djbe** [comment] 2018-10-08 15:04
Refs https://github.com/SwiftGen/SwiftGen/pull/533#discussion_r222101611.

**Comment by AliSoftware** [comment] 2018-10-08 18:32
The warnings generated by `swiftlint` for example start with the path to the file, with line and column if available, then `warning`, so `path:line:col: warning: message` or `path:line: warning: message` or `path: warning: message`

I'm not sure then why those don't show up in Xcode, as if I create a Script build phase to `echo` those same messages, they do show up correctly:

<img width="1620" alt="xcode-warnings-format" src="https://user-images.githubusercontent.com/216089/46626959-3c4c2e00-cb39-11e8-895b-ae83fa6e2316.png">

I think the issue might not be related to the line starting with `warning:` or not (as you see in my attached screenshot, the same output works in my example), but probably because we might print those messages in `stderr` (and not `stdout`) iirc?

**Comment by djbe** [comment] 2018-10-09 20:58
SwiftLint outputs config errors to `stderr`, and those will be invisible to Xcode. SwiftLint warnings are actually just normal output (they don't have deprecation notices afaik). 

We may want to change our warning loggint to `stdout`:
https://github.com/SwiftGen/SwiftGen/blob/master/Sources/SwiftGen/Logs.swift#L49

**Comment by AliSoftware** [comment] 2018-10-09 21:06
Yeah I agree. I think we even could improve our log enum to take optional associated values for file and line and if provided we can include it in the output.

Might even make that conform to `Swift.Error` so we could throw them idk 🤔

**Comment by djbe** [comment] 2018-10-09 21:07
Or we could check for environment variables to detect Xcode, and route everything to `stdout` in that case. From a quick check we could use the existence of something like `XCODE_VERSION_ACTUAL`.

**Comment by AliSoftware** [comment] 2018-10-09 21:15
```
struct LogMessage: Swift.Error {
  let file: String?
  let line: UInt?
  let kind: LogLevel
  let message: String

  init(kind: LogLevel, message: String, file: String? = nil, line: UInt? = nil) { … }
  func log(to: OutputDestination) { … }
}
```
?

**Comment by AliSoftware** [comment] 2018-10-09 21:20
And we could have `extension OutputDestination { static var inferFromContext: OutputDestination { /* … stdout if Xcode, stderr if terminal */ } }`

**Comment by djbe** [comment] 2020-07-06 21:42
Recently we tried tackling this issue in #729, but during some testing we weren't able to reproduce this issue:
https://github.com/SwiftGen/SwiftGen/pull/729#discussion_r444895183

@Igor-Palaguta Are you still not seeing any SwiftGen warnings (or errors) in Xcode? Our testing happend in Xcode 11.5, maybe Apple fixed the issue since then 🤷

**Comment by djbe** [comment] 2020-10-07 23:38
Closing this due to inactivity

**Closed by djbe** 2020-10-07 23:38 UTC
Labels: status: awaiting input
