### ISSUE TITLE
Storyboards swift4 template fails

### ISSUE THREAD

**Issue by mikkelam** [SwiftGen/SwiftGen#443] opened 2018-06-28 13:14 UTC
Hi, I have a problem with the swift4 storyboard template. I'm using the newest version of swiftgen and i have the folowing config
```
storyboards:
  paths: 'Controllers/'
  templateName: swift4
  output: 'Storyboards.swift'
```

The template generates files like so:
```
...
import App_Name 
...


internal enum StoryboardScene {
  internal enum Something: StoryboardType {
    internal static let storyboardName = "Something"

    internal static let searchResultsViewController = SceneType<App_Name.SearchResultsViewController>(storyboard: Something.self, identifier: "SearchResultsViewController")
  }
```

Which always fails as the file is inside App_Name module already. I've tried various module params yet it doesn't fix it. Do you guys have any idea?

If it helps my module has two targets:
- App_Name 
- App_Name_Dev

which use the same files, it's just used for deployment

**Comment by djbe** [comment] 2018-06-28 14:06
This is a duplicate of #405, and some other issues. Quick solutions:
- Provide the module in the storyboard as `--param module=App_Name`
- Write your own template that ignores both `App_Name` and `App_Name_Dev`.

Quick tip: use configurations instead of targets for multiple environments.

**Closed by djbe** 2018-06-28 14:06 UTC

**Comment by mikkelam** [comment] 2018-07-04 08:02
Yeah like i said, i tried that. Doing that it correctly removes the statement `import App_Name`
yet it still adds `App_name` to my scenetypes. Anyway thanks for your reply and time

**Comment by djbe** [comment] 2018-07-04 08:19
It shouldn't do that? 😕 
What if you add the `ignoreTargetModule` flag?

**Comment by mikkelam** [comment] 2018-07-05 13:18
that's also not working :/

**Comment by djbe** [comment] 2018-07-05 13:55
Then I suggest you try the 2nd solution I originally mentioned, copying the existing template and modifying it to check for all your available targets. At least until #435 is implemented.
