### ISSUE TITLE
It's possible to create a struct of all files inside one folder?

### ISSUE THREAD

**Issue by AFcgi** [SwiftGen/SwiftGen#496] opened 2018-09-12 20:34 UTC
Similar to the storyboards, there should be a template, which summarizes files from a folder with subfolders in a struct. Do you have any idea to realize this with the upcoming version 6.0?

Example output:
```
struct File {
	var name: String

	// MARK: - Getter
	var path: String {

		let bundle = Bundle(for: BundleToken.self)
		return bundle.path(forResource: self.name, ofType: nil) ?? ""
	}
	var url: URL {
		return URL(fileURLWithPath: self.path)
	}


	enum Html {
		/// test.html
		static let test = File(name: "test.html")
	}
	enum Json {
		/// test.json
		static let test = File(name: "test.json")
	}
}

private final class BundleToken {}
```

**Comment by djbe** [comment] 2018-09-12 22:28
Dupe of several issues.

Depending on what you want to achieve, these are the issues you may want to take a look at:
- Load JSON/Plist/YAML files in a structured way: use the new parsers for these when 6.0 is released.
- Specifically for XIBs: #235 
- Have SwiftGen generate a listing of files in folders: #284 and #146

**Closed by djbe** 2018-09-12 22:28 UTC
