### ISSUE TITLE
How to unit test the strings generated by SwiftGen?

### ISSUE THREAD

**Issue by Kalzem** [SwiftGen/SwiftGen#579] opened 2019-01-19 18:28 UTC
I am using Lokalize.co to handle all i18n/l10n wording.
A script fetches them from Lokalize.co api and generates the different Localizable.strings, then SwiftGen does its stuff to generate the Strings.swift file.

The thing is that sometimes translators break dynamic wordings, which ends in a nice app crash.

I would like to unit test all the static func of Strings.swift and see if they are fine or not in all the available languages.

So I have 2 goals:
(1) Get the list of all static func
(2) Change at runtime the language of the enum in Strings.swift

Are there any attempt or WIP for these?

**Comment by AliSoftware** [comment] 2019-01-19 18:41
Hi @BabyAzerty

In your case if you want to unit test your strings I think the best option is to create a custom Stencil template for your tests, which instead of generating the code that you get with the default template, would generate stuff only useful for your unit tests, including for example (1) an array of all the strings found by SwiftGen so you could iterate on them if needed in your tests to check them all (2) a way to inject a specific locale instead of having the code use the current Locale

Hey if you go that route, you might even use SwiftGen to … directly generate the unit tests themselves using a custom template I guess, would be even more powerful!

PS: If you don't have experience creating your own Stencil templates for SwiftGen, don't hesitate to look in the Documentation folder of the repo for more info

**Comment by djbe** [comment] 2019-01-19 22:13
@BabyAzerty what are the crashes caused by? Translators changing the string format specifiers? `%@` to `%d` (or something similar)? Because you could catch such issues by running swiftgen for each translation strings file, and checking if there are any diffs.

**Comment by AliSoftware** [comment] 2019-01-19 23:07
One idea would be, again with a custom template, to generate a list of {key: listOfParamTypes} pairs (in text, XML Plist, JSON, whatever fits better for your tests) for each language.

Then your unit test will ensure that this Dictionary is not changing, always the same for all languages.

That way if a translator messes up, you'll see an entry like `home.welcome.message: String, Int` becoming `home.welcome.message: Int, String` in that custom-template-generated dict for that language and see that the translator messed up that particular key for that language.

**Comment by AliSoftware** [comment] 2019-01-19 23:08
PS: Thomas said you shouldn't work on the weekend 😛

**Comment by BabyAzerty** [comment] 2019-01-21 11:03
Thanks for the replies. Creating a custom Stencil sounds about right, I'll dig into it 😄 Especially the key: listOfParamTypes solution!

(PS: Didn't work this Sunday /o/)

**Comment by AliSoftware** [comment] 2019-02-02 23:27
@BabyAzerty closing this as I think the question has been answered (create a dedicated template for this), but feel free to reopen if you have further questions.

**Closed as completed by AliSoftware** 2019-02-02 23:27 UTC
Labels: type: question
