### ISSUE TITLE
Add support for bundle folder

### ISSUE THREAD

**Issue by woloda375** [SwiftGen/SwiftGen#109] opened 2016-04-08 08:04 UTC
Hi,

please add support for items in Resources.bundle e.g.: Resources.bundle/images/myimage@2x.png. 

We use bundle folders for easy collaboration with designers. They behave like referenced folders in Xcode, no change to the .pbxproj file for easy GIT. No need to handle .xcassets JSON structure, no slow drag-&-drop of resources in Xcode, no problems with resources renaming and moving. Designers just export PNGs into the bundle and push to GIT repository. No need to learn designers anything about the Xcode and GIT conflicts resolving.

Bundles have too many pluses to not to use them.

**Comment by AliSoftware** [comment] 2016-05-30 06:24
I think #108 would help address this feature. Don't hesitate to contribute to it to make it happen.

**Comment by djbe** [comment] 2018-07-05 15:41
Closing this as a dupe of #235 and #146.

**Closed by djbe** 2018-07-05 15:41 UTC
Labels: type: enhancement
