### ISSUE TITLE
Problem with generating Assets enum

### ISSUE THREAD

**Issue by idevAgg** [SwiftGen/SwiftGen#744] opened 2020-07-07 10:54 UTC
I use SwiftGen for generate sources for localization and assets in my project, but something went wrong few days ago. Asset's enum not generating after the project building. There is no problems with .strings files, only with .xcassets. Maybe you know in which case it can be? Usage:  
.sh file:
<img width="610" alt="Снимок экрана 2020-07-07 в 13 51 56" src="https://user-images.githubusercontent.com/50491957/86770255-14189880-c059-11ea-9c8c-f5732fb98430.png">
Build Phases
<img width="1791" alt="Снимок экрана 2020-07-07 в 13 52 57" src="https://user-images.githubusercontent.com/50491957/86770332-35798480-c059-11ea-9064-6b549d73e0c8.png">
source  files: 
<img width="231" alt="Снимок экрана 2020-07-07 в 13 53 48" src="https://user-images.githubusercontent.com/50491957/86770445-5cd05180-c059-11ea-947c-79d2d562be32.png">

**Comment by djbe** [comment] 2020-07-07 11:28
What version of SwiftGen are you using? Because if it's SwiftGen 6.2 or higher, we obsoleted (removed) the `swift3` templates.

Also, it's highly recommended to use a configuration file:
- You can `lint` your setup and see if everything is correct (wrong paths, missing templates, outdated commands, etc..)
- You get a performance boost because SwiftGen can run parsers in parallel

**Comment by idevAgg** [comment] 2020-07-07 11:38
Podfile.lock:
- SwiftGen (6.2.1) 
What do you recommend? Do you have some new template for assets? Or just use some specify version of SwiftGen?

**Comment by djbe** [comment] 2020-07-07 11:44
An example config file in your  case (based on what I can see above), would be:
```yaml
input_dir: w2w/Resources
output_dir: w2w/Resources
strings:
  inputs: en.lproj/Localizable.strings
  outputs:
    templateName: structured-swift5
    output: L10n.swift
xcassets:
  inputs: Assets.xcassets
  outputs:
    templateName: swift5
    output: Assets.swift
```

A quick how-to about configuration files can be found here: https://github.com/SwiftGen/SwiftGen#configuration-file

Note: I've taken the liberty of choosing `swift5` templates. There aren't any (big) differences between the `swift4` and `swift5` templates.

**Comment by idevAgg** [comment] 2020-07-07 13:03
I created the swiftgen.yml file and added it to my project with the content you provided, and changed my .sh file:
<img width="566" alt="Снимок экрана 2020-07-07 в 15 59 23" src="https://user-images.githubusercontent.com/50491957/86785136-f48a6b80-c06a-11ea-96bc-59c6a12eb079.png">
Is that all I need to do? Everything is working correctly.

**Comment by djbe** [comment] 2020-07-07 13:19
No read the instructions I mentioned above. Your build step should look like:
```bash
#!/bin/sh
"$PODS_ROOT/SwiftGen/bin/swiftgen"
```
Nothing more. SwiftGen will automatically load the configuration file, and do it's thing.

Note that yes, your build step as posted in your comment works, but completely ignores the config file you just made. Do one or the other, but not both 😉

**Comment by djbe** [comment] 2020-07-07 22:52
Closing this as the issue is solved. For the curious, the command was referring to a non-existing template (swift3), and thus it was failing.

**Closed as completed by djbe** 2020-07-07 22:52 UTC
Labels: type: question

**Comment by idevAgg** [comment] 2020-07-08 06:07
Success! Thanks for the quick response. My regards
