### ISSUE TITLE
Swiftgen configuration file

### ISSUE THREAD

**Issue by TarekSalama** [SwiftGen/SwiftGen#477] opened 2018-09-04 16:44 UTC
I have this `swiftgen.yml` configuration file:
```
fonts:
  paths: 
    - Resources/Fonts
  outputs:
    - templateName: swift4
    - output: Managers/FontManager.swift
colors:
  paths: 
    - Resources/Colors.txt
  outputs:
    - templateName: swift4
    - output: Managers/ColorManager.swift
xcassets:
  paths:
    - Resources/Assets.xcassets
  outputs:
    - templateName: swift4
    - output: Managers/ImageManager.swift
```

and I keep getting the following error every time I run `swiftgen` from the terminal:
```
You must specify a template name (-t) or path (-p).

To list all the available named templates, use 'swiftgen templates list'
```

What am I missing here? I have the homebrew version which does a system-wide installation.

**Comment by djbe** [comment] 2018-09-04 16:46
Hi @TarekSalama,

You probably based your config on the documentation for SwiftGen 6.0, which isn't out yet (especially because you're using `outputs`, which is new).

To see the documentation for the latest release, 5.3.0: https://github.com/SwiftGen/SwiftGen/tree/5.3.0

**Comment by djbe** [comment] 2018-09-04 16:46
Closing this as a dupe of #431.

**Closed by djbe** 2018-09-04 16:46 UTC
